= PortScan_Linux
 
== Explanation 
=== Participants: Christos Vasileiou 19390032
              Ioannis  Bouras    19390160
=== Description : This application is designed to run Scans to the ports
of your network. It uses nmap in order to execute those scans. At first 
you will need to open the application with a password. 
The password is "1234" or "1111"!
The password windows is connected with an sql database that contains all 
the passwords. In order to add a password you need to do it manually!
The window that pops after contains one TextField , three Buttons , 
one output Text Area and a progress bar. 
The first button uses the ip that you write to the Text Field and uses 
nmap to run a TCP Scan.
The second button executes the ifconfig -a command in order to find your ip.
The third button executes multiple scans. In order to work write your ip with
this form 192.168.1 and the application will add .1 , .2 etc until .255 and 
show for each ip all the open ports. Under the Output Text Area is the 
progressbar that is running with the multiple scans button. The java 
application is running through a docker and the sql database through an 
other docker. A connector is in place in order to communicate.

In order the application to run you need to have JDK 19 , HyperX11 for the 
GUI in the docker , Docker app etc for the containers. 
You press the install.sh for the sql docker to start, to build the Java 
application container and run the Java Container.  
 
